version: "3.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - slurm
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: honorlessman/slurm-manager:1.0
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - slurm
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: honorlessman/slurm-manager:1.0
    command: ["slurmctld"]
    hostname: slurmctld
    container_name: slurmctld
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - slurm
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

networks:
  slurm:
    driver: overlay

volumes:
  etc_munge:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.105,rw
      device: ":/nfs/etc_munge"
  etc_slurm:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.105,rw
      device: ":/nfs/etc_slurm"
  slurm_jobdir:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.105,rw
      device: ":/nfs/slurm_jobdir"
  var_log_slurm:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.105,rw
      device: ":/nfs/var_log_slurm"
  login_home:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.105,rw
      device: ":/nfs/home"
  var_lib_mysql: