version: "3.0"

services:
    c1:
      image: honorlessman/slurm-worker:1.0
      command: ["slurmd"]
      hostname: c1
      container_name: c1
      deploy:
        placement:
          constraints:
            - node.role == worker
      networks:
        - manager_slurm
      volumes:
        - etc_munge:/etc/munge
        - etc_slurm:/etc/slurm
        - slurm_jobdir:/data
        - var_log_slurm:/var/log/slurm
      expose:
        - "6818"

volumes:
  etc_munge:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.107,rw
      device: ":/nfs/etc_munge"
  etc_slurm:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.107,rw
      device: ":/nfs/etc_slurm"
  slurm_jobdir:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.107,rw
      device: ":/nfs/slurm_jobdir"
  var_log_slurm:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.107,rw
      device: ":/nfs/var_log_slurm"

networks:
  manager_slurm:
    external: true
